FROM node:16-buster-slim

#RUN apk add --no-cache libc6-compat

WORKDIR /var/www/html

COPY package*.json ./
RUN npm install

#COPY ./ ./

CMD [ "npm", "run", "dev" ]


#working version but no hot reload
# FROM node:16-alpine

# RUN apk add --no-cache libc6-compat

# WORKDIR /var/www/html

# COPY ./frontend/package*.json ./
# RUN npm ci
# RUN npm install next typescript -g

# COPY ./frontend ./

# RUN npm run build

# CMD [ "npm", "start" ]
