tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "mongodb/brew"
brew "certbot"
brew "cowsay"
brew "gh"
brew "git", link: false
brew "git-flow"
brew "lcdf-typetools"
brew "magic-wormhole"
brew "node"
brew "telnet"
brew "wget"
brew "heroku/brew/heroku"
brew "mongodb/brew/mongodb-community"
brew "mongodb/brew/mongodb-community-shell", link: false
cask "wormhole"
